updated bucc

diff --git a/bin/bucc b/bin/bucc
--- a/bin/bucc
+++ b/bin/bucc
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 repo_root=$(dirname $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd))
 
 if [ -e "bbl-state.json" ]; then
@@ -64,12 +64,12 @@ cpis() {
 }
 
 validate_vars_file() {
-    # Todo: prettify
+    # TODO: prettify
     local cpi_vars=${repo_root}/ops/cpis/$(cpi)/vars.tmpl
     if [ ! -e $vars_file ]; then
         cp $cpi_vars $vars_file
-        if [ ! $(cpi) = "virtualbox" ]; then
-            echo "We just copied a template in $vars_file please adjust it to your needs"
+        if [ ! $(cpi) = "virtualbox" ] && [ ! $(cpi) = "docker-desktop" ] ; then
+            echo "We just copied a template in $vars_file please adjust it to your needs and run the command again"
             # we should break here or check file contents and see if we still have the right var file for the cpi
             exit 1
         fi
@@ -124,6 +124,10 @@ int_args() (
 
     if [ $(lite) = true ]; then
         ops_files+=(${repo_root}/ops/lite/*.yml)
+        local cpi_lite_ops_dir="${repo_root}/ops/cpis/$(cpi)/lite"
+        if [ -d "${cpi_lite_ops_dir}" ]; then
+            ops_files+=(${cpi_lite_ops_dir}/*.yml)
+        fi
     fi
 
     ops_files+=(${repo_root}/ops/*.yml)
@@ -173,6 +177,7 @@ usage() {
     echo "  bbr -- wrapper for bbr cli"
     echo "  routes -- add routes for virtualbox"
     echo "  test -- check if all systems are operational"
+    echo "  offline -- create's an offline tarball, setting a path is optional. eg 'bucc offline /mypath/'"
     exit 1
 }
 
@@ -199,6 +204,23 @@ down_usage() {
     echo "  -c | --clean  cleans up your environment by removing state files"
 }
 
+offline_usage() {
+  echo "  --destination  Zip file location (default: /tmp)"
+  echo "  --cpi          Cloud provider: [$(cpis | xargs | sed 's/ /, /g')]"
+  echo "  --lite         Created bosh will use the warden cpi with garden runc"
+  echo "$(ls ${repo_root}/ops/flags | cut -d "." -f 1 | sed 's/^/  --/')"
+  echo ""
+  echo "  Optional cpi specific flags:"
+
+  local cpis_dir=${repo_root}/ops/cpis
+  for cpi in $(cpis); do
+      local flags_dir=${repo_root}/ops/cpis/${cpi}/flags
+      if [ -d ${flags_dir} ]; then
+          echo "    ${cpi}: $(ls ${flags_dir} | cut -d "." -f 1 | sed 's/^/--/' | xargs)"
+      fi
+  done
+}
+
 platform() {
     if [ "$(uname)" == "Darwin" ]; then
         echo "darwin"
@@ -218,6 +240,15 @@ faketty() {
     esac
 }
 
+run_hook() {
+    local hook=${repo_root}/ops/cpis/$(cpi)/${1}.sh
+    if [ -f ${hook} ]; then
+        echo "Running ${1} hook: ${hook}"
+        ${hook} ${vars_file}
+        echo ""
+    fi
+}
+
 up() {
     local flags="--cpi $(cpi)"
     local skip_drain="--skip-drain"
@@ -234,7 +265,9 @@ up() {
         echo -e "bosh create-env ${skip_drain} $(int_args | sed 's/yml/yml \\ \\n/g') ${state_arg}\n"
     fi
 
-    bosh create-env ${skip_drain} $(int_args) ${state_arg} "$@"
+    run_hook "pre-up"
+
+    bosh --tty create-env ${skip_drain} $(int_args) ${state_arg} "$@"
 }
 
 down() {
@@ -244,7 +277,10 @@ down() {
       exit 1
     fi
 
-    bosh delete-env ${skip_drain} $(int_args) ${state_arg} "$@"
+    bosh --tty delete-env ${skip_drain} $(int_args) ${state_arg} "$@"
+
+    run_hook "post-down"
+
     echo "you can use the clean command if your are planning to use a new cpi or ip"
 }
 
@@ -253,16 +289,24 @@ clean() {
     echo "your environment is still running, please tear it down with 'bucc down --clean'"
     exit 1
   fi
-  rm -rf ${state}
+  rm -rf ${state} "${project_root}/operators" "${project_root}/src/offline_resources"
   mv ${vars_file} ${vars_file}.bck
   echo "'state' dir has been cleaned and 'vars.yml' has been moved to 'vars.yml.bck'"
   echo "to also cleanup your current shell run `source <(bucc env --clean)`"
 }
 
+clean_bosh_downloads() {
+    shas=$(int --path /releases | grep sha1: | awk '{print $2}')
+    shas="${shas}\n$(int --path /resource_pools/name=vms/stemcell/sha1)"
+    match=$(echo "${shas}" | xargs | sed 's/ /\\|/g')
+    pushd ~/.bosh/downloads
+    ls | grep -v "${match}" | xargs rm
+}
+
 vars() {
     bosh int ${vars_file}
     echo "bosh_environment: $(ip)"
-    echo "bosh_target: $(ip)"
+    echo "bosh_target: https://$(ip):25555"
     echo "bosh_ca_cert: |"
     echo "$(cat $(ca_cert) | sed 's/^/  /')"
     echo "bosh_client: admin"
@@ -270,10 +314,10 @@ vars() {
     echo "credhub_url: $(int --path /instance_groups/0/properties/director/config_server/url | rev | cut -c6- | rev)"
     echo "credhub_username: credhub-admin"
     echo "credhub_password: $(int --path /instance_groups/0/jobs/name=uaa/properties/uaa/clients/credhub-admin/secret)"
-    echo "vault_url: https://$(int --path /instance_groups/0/jobs/name=vault-credhub-proxy/properties/address)"
-    echo "concourse_url: $(int --path /instance_groups/0/jobs/name=atc/properties/external_url)"
-    echo "concourse_username: $(int --path /instance_groups/0/jobs/name=atc/properties/add_local_users/0 | cut -d: -f1)"
-    echo "concourse_password: $(int --path /instance_groups/0/jobs/name=atc/properties/add_local_users/0 | cut -d: -f2)"
+    echo "vault_url: https://$(ip):8200"
+    echo "concourse_url: $(int --path /instance_groups/0/jobs/name=web/properties/external_url)"
+    echo "concourse_username: $(int --path /instance_groups/0/jobs/name=web/properties/add_local_users/0 | cut -d: -f1)"
+    echo "concourse_password: $(int --path /instance_groups/0/jobs/name=web/properties/add_local_users/0 | cut -d: -f2)"
     echo "concourse_ca_cert: |"
     echo "$(cat $(ca_cert) | sed 's/^/  /')"
 }
@@ -320,6 +364,7 @@ env() {
     echo "export BOSH_GW_USER=$(int --path /instance_groups/name=bosh/jobs/name=user_add/properties/users/0/name)"
     echo "export BOSH_GW_HOST=$(ip)"
     echo "export BOSH_GW_PRIVATE_KEY=$(ssh_private_key jumpbox_ssh)"
+    echo "export CREDHUB_SERVER=$(get_var credhub_url)"
     echo "export CREDHUB_CLIENT=$(get_var credhub_username)"
     echo "export CREDHUB_SECRET=$(get_var credhub_password)"
     echo "export CREDHUB_CA_CERT=$(ca_cert)"
@@ -401,7 +446,7 @@ _bosh() {
         bosh log-in -e "$(_alias)"
 }
 
-_credhub() {
+_credhub_download() {
     local url="https://github.com/cloudfoundry-incubator/credhub-cli/releases/download"
     local version=$(grep credhub ${repo_root}/.versions | cut -d= -f2)
     local cli_path=${repo_root}/bin/credhub
@@ -415,14 +460,18 @@ _credhub() {
       mv credhub ${repo_root}/bin/
       popd
     fi
+}
 
+_credhub() {
+    _credhub_download
+    local cli_path=${repo_root}/bin/credhub
     ${cli_path} login --server $(get_var credhub_url) \
             --ca-cert $(ca_cert) \
             --client-name $(get_var credhub_username) \
             --client-secret $(get_var credhub_password)
 }
 
-_safe() {
+_safe_download() {
     local url="https://github.com/starkandwayne/safe/releases/download"
     local version=$(grep safe ${repo_root}/.versions | cut -d= -f2)
     local cli_path=${repo_root}/bin/safe
@@ -435,13 +484,17 @@ _safe() {
       mv safe ${repo_root}/bin/
       popd
     fi
+}
 
-    ${cli_path} target -k $(get_var vault_url) $(_alias)
-    echo $(get_var credhub_username):$(get_var credhub_password) | ${cli_path} auth token
+_safe() {
+  _safe_download
+  local cli_path=${repo_root}/bin/safe
+  ${cli_path} target -k $(get_var vault_url) $(_alias)
+  echo $(get_var credhub_username):$(get_var credhub_password) | ${cli_path} auth token
 }
 
 
-_bbr() {
+_bbr_download() {
     local url="https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download"
     local version=$(grep bbr ${repo_root}/.versions | cut -d= -f2)
     local cli_path=${repo_root}/bin/bbr
@@ -458,7 +511,11 @@ _bbr() {
       fi
       popd
     fi
+}
 
+_bbr() {
+    _bbr_download
+    local cli_path=${repo_root}/bin/bbr
     local user=$(int --path /instance_groups/name=bosh/jobs/name=user_add/properties/users/0/name)
     ${cli_path} director --host $(ip) --username ${user} --private-key-path $(ssh_private_key jumpbox_ssh) "$@"
 }
@@ -498,22 +555,25 @@ _uaac() {
     faketty uaac token client get uaa_admin --secret $(int --path /instance_groups/0/jobs/name=uaa/properties/uaa/clients/uaa_admin/secret)
 }
 
-_uaa() {
-    local url="https://github.com/starkandwayne/uaa-cli-releases/releases/download"
+_uaa_download() {
+    local url="https://github.com/cloudfoundry-incubator/uaa-cli/releases/download"
     local version=$(grep uaa ${repo_root}/.versions | cut -d= -f2)
     local cli_path=${repo_root}/bin/uaa
 
     if ! ( [ -f ${cli_path} ] && ${cli_path} version | head -n 1 | grep ${version} > /dev/null); then
       echo "installing uaa cli '${version}' into: ${repo_root}/bin/"
       pushd $(mktemp -d)
-      curl -s -L >uaa "${url}/v${version}/uaa-$(platform)-amd64"
+      curl -s -L >uaa "${url}/${version}/uaa-$(platform)-amd64-${version}"
       chmod +x uaa
       mv uaa ${repo_root}/bin/
       popd
     fi
+}
 
-    faketty uaa target $(int --path /instance_groups/0/jobs/name=uaa/properties/uaa/url) --skip-ssl-validation
-    faketty uaa get-client-credentials-token uaa_admin --client_secret $(int --path /instance_groups/0/jobs/name=uaa/properties/uaa/clients/uaa_admin/secret)
+_uaa() {
+  _uaa_download
+  faketty uaa target $(int --path /instance_groups/0/jobs/name=uaa/properties/uaa/url) --skip-ssl-validation
+  faketty uaa get-client-credentials-token uaa_admin --client_secret $(int --path /instance_groups/0/jobs/name=uaa/properties/uaa/clients/uaa_admin/secret)
 }
 
 store_int() {
@@ -528,7 +588,7 @@ int() {
 }
 
 ip() {
-    int --path /networks/name=default/subnets/0/static/0
+    get_var internal_ip
 }
 
 ssh_private_key() {
@@ -543,6 +603,17 @@ jump() {
     echo $BOSH_ALL_PROXY | sed -e 's$ssh+socks5://\(.*\):.*=\(.*\)$-o "ProxyCommand=ssh \1 -i \2 nc %h %p"$g'
 }
 
+_scp() {
+    tmp_config=$(mktemp)
+    if [[ "$BOSH_ALL_PROXY" == "ssh+socks5"* ]]; then
+        echo $BOSH_ALL_PROXY | sed -e 's$ssh+socks5://\(.*\):\(.*\)?.*=\(.*\)$ProxyCommand ssh -W %h:%p \1 -p \2 -i \3$g' > ${tmp_config}
+    fi
+    local user=$(int --path /instance_groups/name=bosh/jobs/name=user_add/properties/users/0/name)
+    cmd="scp -i $(ssh_private_key jumpbox_ssh) -F ${tmp_config} $1 $user@$(ip):$2"
+
+    ${cmd}
+    rm ${tmp_config}
+}
 _ssh() {
     tmp_config=$(mktemp)
     if [[ "$BOSH_ALL_PROXY" == "ssh+socks5"* ]]; then
@@ -550,6 +621,7 @@ _ssh() {
     fi
     local user=$(int --path /instance_groups/name=bosh/jobs/name=user_add/properties/users/0/name)
     cmd="ssh -i $(ssh_private_key jumpbox_ssh) -F ${tmp_config} $user@$(ip)"
+
     if [ $# -eq 0 ]; then
         ${cmd} -t 'command; sudo su -'
     else
@@ -603,6 +675,93 @@ smoke_tests() {
     safe gen secret/account passphrase
     safe get secret/account
     safe delete secret/account
+}
+
+offline() {
+  set -e
+  echo "Checking for missing dependecies"
+  _credhub_download
+  _bbr_download
+  _uaa_download
+  _safe_download
+
+  yml_filelocation=${project_root}/operators
+  offline_filelocation=${project_root}/src/offline_resources
+
+  release_names=$(int --path /releases | grep name: | awk '{print $3}')
+
+  echo "Downloading releases this can take a while!"
+  temp_dir=$(mktemp -d)
+  trap "rm -rf ${temp_dir}" EXIT
+  mkdir -p ${yml_filelocation} ${offline_filelocation}
+  pushd ${temp_dir}
+  for release_name in $release_names; do
+
+    version=$(int --path /releases/name=$release_name/version)
+    url=$(int --path /releases/name=$release_name/url)
+    sha1=$(int --path /releases/name=$release_name/sha1)
+    filename="${release_name}-${version}.tgz"
+
+    if [ ! -f "${offline_filelocation}/${filename}" ]; then
+      echo "Starting to Download ${release_name}-release"
+      curl --retry 5 -s -f -o ${filename} -L ${url}
+
+      cat > "9x-${release_name}-offfline-compiled-release.yml" <<YML
+      - type: replace
+        path: /releases/name=${release_name}?
+        value:
+          name: ${release_name}
+          version: ${version}
+          url: "file://../offline_resources/${filename}"
+          sha1: ${sha1}
+YML
+    echo "Moving files for ${release_name}-release"
+    mv *.yml ${yml_filelocation} &>/dev/null
+    mv *.tgz ${offline_filelocation} &>/dev/null
+    echo "Downloaded ${release_name}-release"
+  else
+    echo "Release ${release_name}-release was already downloaded"
+  fi
+  done
+
+  stemcell_sha1=$(int --path /resource_pools/name=vms/stemcell/sha1)
+  stemcell_url=$(int --path /resource_pools/name=vms/stemcell/url)
+  # TODO: getting the name could be handled better
+  stemcell_name=$(echo ${stemcell_url} | cut -d "-" -f 6,7,8,9)
+  # TODO: make get version more robust
+  stemcell_version=$(echo ${stemcell_url} | cut -d "/" -f5)
+  stemcell_filename="${stemcell_name}-${stemcell_version}.tgz"
+
+  if [ ! -f "${yml_filelocation}/9x-stemcell-offfline-stemcell.yml" ]; then
+    echo "Starting to download stemcell"
+    curl --retry 5 -s -f -o ${stemcell_filename} -L ${stemcell_url}
+    cat > "9x-stemcell-offfline-stemcell.yml" <<YML
+    - type: replace
+      path: /resource_pools/name=vms/stemcell?
+      value:
+        url: "file://../offline_resources/${stemcell_filename}"
+        sha1: ${sha1}
+YML
+    echo "Moving files for ${stemcell_name}-release"
+    mv *.yml ${yml_filelocation} &>/dev/null
+    mv *.tgz ${offline_filelocation} &>/dev/null
+    echo "Downloaded ${stemcell_name}-release"
+  else
+    echo "Stemcell ${stemcell_name} ${stemcell_version} was already downloaded"
+  fi
+  popd
+
+  echo "Compressing files"
+  # FIXME: for some reason gloabl version variable is not used, but the version of the last release in the manifest
+  version=$(grep bucc ${repo_root}/.versions | cut -d= -f2)
+  filelocation=${1}
+  tarfile=${filelocation}/bucc-${version}.tar.gz
+  mkdir -p ${filelocation}
+  parentdir=$(dirname ${project_root})
+  dirname=$(basename ${project_root})
+  tar -zcf ${tarfile} -C ${parentdir} ${dirname}
+  echo "Your file is located in ${tarfile}"
+
 }
 
 _ensure_bosh_cli_installed
@@ -672,6 +831,10 @@ case "$1" in
         clean "$@"
         ;;
 
+    clean_downloads)
+        clean_bosh_downloads "$@"
+        ;;
+
     bosh)
         _bosh "$@"
         ;;
@@ -727,6 +890,10 @@ case "$1" in
         shift
         _ssh "$@"
         ;;
+    scp)
+        shift
+        _scp "$@"
+        ;;
 
     rotate-certs)
         shift
@@ -744,6 +911,47 @@ case "$1" in
 
     test)
         smoke_tests
+        ;;
+
+    offline)
+        shift
+        # TODO: by default virtualbox is used we need a good check
+        if [ $# -eq 0 ] ; then
+            echo "Usage: $1 [--cpi] [--lite] [--destination] [flags] [-h|--help]"
+            exit 1
+        fi
+        destination=${TMPDIR:-/tmp}
+        while [[ $# -gt 0 ]]; do
+            case "$1" in
+                -h|--help|help)
+                    offline_usage # TODO: write offline_usage
+                    exit 0
+                    ;;
+                --cpi)
+                    echo "$2" > ${state}/cpi
+                    shift
+                    ;;
+                --cpi=*)
+                    echo "${1#*=}" > ${state}/cpi
+                    ;;
+                --lite)
+                    echo "true" > ${state}/lite
+                    ;;
+                --destination)
+                    destination=${2%/}
+                    shift
+                    ;;
+                *)
+                    echo ${1#*--} >> ${state}/flags
+            esac
+            shift
+        done
+        normalize_flags
+        validate_cpi
+        validate_vars_file
+        validate_cpi_flags
+
+        offline "${destination}"
         ;;
 
     *)
